// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using BigMachines;

#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS1998

namespace BigMachines.Generator
{
    static class Generated
    {
        internal static void RegisterBM()
        {
            Sandbox.TinyMachine.RegisterBM(721092537);
            Sandbox.ParentClass.RegisterBM();
        }
    }
}

namespace BigMachines
{
    public static class BigMachinesModule_Sandbox
    {
        private static bool Initialized;

        [ModuleInitializer]
        public static void Initialize()
        {
            if (Initialized) return;
            Initialized = true;

            BigMachines.Generator.Generated.RegisterBM();
        }
    }
}
